<?php
/**
 * Template File
 * This file is the help message template for the Admin Help tab of the Views listing page.
 *
 * @since 2.5.0
 */
?>

<p><?php echo __( 'Use <strong>Views</strong> to load content from the database and display it anyway you choose.', 'wpv-views' ); ?></p>
<p><?php echo __( 'This page lists the <strong>Views</strong> in your site. You have contextual actions to ‘duplicate’ and ‘delete’ Views. You can also perform bulk actions.', 'wpv-views' ); ?></p>
<p><?php echo __( 'Click on a <strong>Views</strong> name to edit it or create new Views.',  'wpv-views' ); ?></p>
<p>
	<a href="https://toolset.com/course-lesson/creating-a-view/?utm_source=plugin&utm_medium=gui&utm_campaign=blocks" target="_blank"><?php echo __( 'Views online help',  'wpv-views' ); ?></a>
</p>
