<?php
/**
 * Template File
 * This file is the help message template for the Admin Help tab of the WordPress Archives edit page.
 *
 * @since 2.5.0
 */
?>

<p><?php echo __( '<strong>WordPress Archives</strong> let you style and design standard listing and archive pages.', 'wpv-views' ); ?></p>
<p><?php echo __( 'To create a <strong>WordPress Archive</strong>:', 'wpv-views' ); ?></p>
<ol>
    <li><?php echo __( 'Set the title', 'wpv-views' ); ?></li>
    <li><?php echo __( 'Select on which listing pages it displays', 'wpv-views' ); ?></li>
    <li><?php echo __( 'Design the output for the WordPress Archive by inserting fields and styling with HTML', 'wpv-views' ); ?></li>
</ol>
<p>
    <a href="https://toolset.com/course-lesson/creating-a-custom-archive-page/?utm_source=plugin&utm_medium=gui&utm_campaign=blocks" target="_blank"><?php echo __( 'WordPress Archives online help', 'wpv-views' ); ?></a>
</p>
