<?php
/**
 * Template File
 * This file is the help message template for the Admin Help tab of the WordPress Archives listing page.
 *
 * @since 2.5.0
 */
?>

<p><?php echo __( 'Use <strong>WordPress Archives</strong> to style and design standard listing and archive pages.','wpv-views' ); ?></p>
<p><?php echo __( 'This page lists the <strong>WordPress Archives</strong> in your site.', 'wpv-views' ); ?></p>
<p><?php echo __( 'The tabs menu at the top of the page lets you list the <strong>WordPress Archives</strong> by their name or by how they are used in the site.', 'wpv-views' ); ?></p>
<p><?php echo __( 'Click on the name of a <strong>WordPress Archives</strong> to edit it or create new WordPress Archives using the ‘Add’ buttons.', 'wpv-views' ); ?></p>
<p>
	<a href="https://toolset.com/course-lesson/creating-a-custom-archive-page/?utm_source=plugin&utm_medium=gui&utm_campaign=blocks" target="_blank"><?php echo __( 'WordPress Archives online help', 'wpv-views' ) ; ?></a>
</p>
